# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'formk.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_kontrless(object):
    def setupUi(self, kontrless):
        kontrless.setObjectName("kontrless")
        kontrless.resize(939, 868)
        kontrless.setDocumentMode(False)
        kontrless.setDockNestingEnabled(False)
        self.centralwidget = QtWidgets.QWidget(kontrless)
        self.centralwidget.setObjectName("centralwidget")
        self.closebutton = QtWidgets.QPushButton(self.centralwidget)
        self.closebutton.setGeometry(QtCore.QRect(880, 0, 51, 41))
        self.closebutton.setMouseTracking(False)
        self.closebutton.setStyleSheet("QPushButton{\n"
"border: 1px solid #555;\n"
"padding: 5 px ;\n"
"border-top-right-radius: 11px;\n"
"background: black;\n"
"}\n"
"QPushButton:hover { background: rgba(255,255,255,.2); }\n"
"QPushButton:pressed { background: white; }")
        self.closebutton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("photos/крестик.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closebutton.setIcon(icon)
        self.closebutton.setDefault(False)
        self.closebutton.setObjectName("closebutton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 861, 41))
        self.label.setStyleSheet("QLabel{\n"
"    font: 75 italic 22pt \"MS Sans Serif\";\n"
"color: white;\n"
"border: 1px solid #555;\n"
"border-top-left-radius: 11px;\n"
"background: black;\n"
"font-weight: 3;\n"
"text-transform: capitalize;\n"
"font-size: 25;\n"
"}")
        self.label.setObjectName("label")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 50, 921, 751))
        self.tabWidget.setStyleSheet("background:black;\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.rules = QtWidgets.QWidget()
        self.rules.setObjectName("rules")
        self.textBrowser = QtWidgets.QTextBrowser(self.rules)
        self.textBrowser.setGeometry(QtCore.QRect(40, 10, 841, 651))
        self.textBrowser.setObjectName("textBrowser")
        self.tomain = QtWidgets.QPushButton(self.rules)
        self.tomain.setGeometry(QtCore.QRect(800, 670, 101, 41))
        self.tomain.setStyleSheet("QPushButton {\n"
"  display: inline-block;\n"
"  color: white;\n"
"  text-decoration: none;\n"
"  user-select: none;\n"
"  outline: none;\n"
"  border: 2px solid white;\n"
"  border-radius: 1px;\n"
"  transition: 0.2s;\n"
"} \n"
"QPushButton:hover { background: rgba(255,255,255,.2); }\n"
"QPushButton:pressed { background: white; }")
        self.tomain.setObjectName("tomain")
        self.tabWidget.addTab(self.rules, "")
        self.ex1 = QtWidgets.QWidget()
        self.ex1.setObjectName("ex1")
        self.tomain1 = QtWidgets.QPushButton(self.ex1)
        self.tomain1.setGeometry(QtCore.QRect(800, 670, 101, 41))
        self.tomain1.setStyleSheet("QPushButton {\n"
"  display: inline-block;\n"
"  color: white;\n"
"  text-decoration: none;\n"
"  user-select: none;\n"
"  outline: none;\n"
"  border: 2px solid white;\n"
"  border-radius: 1px;\n"
"  transition: 0.2s;\n"
"} \n"
"QPushButton:hover { background: rgba(255,255,255,.2); }\n"
"QPushButton:pressed { background: white; }")
        self.tomain1.setObjectName("tomain1")
        self.go1 = QtWidgets.QPushButton(self.ex1)
        self.go1.setGeometry(QtCore.QRect(680, 670, 101, 41))
        self.go1.setStyleSheet("QPushButton {\n"
"  display: inline-block;\n"
"  color: white;\n"
"  text-decoration: none;\n"
"  user-select: none;\n"
"  outline: none;\n"
"  border: 2px solid white;\n"
"  border-radius: 1px;\n"
"  transition: 0.2s;\n"
"} \n"
"QPushButton:hover { background: rgba(255,255,255,.2); }\n"
"QPushButton:pressed { background: white; }")
        self.go1.setObjectName("go1")
        self.exe1 = QtWidgets.QLabel(self.ex1)
        self.exe1.setGeometry(QtCore.QRect(10, 10, 901, 61))
        self.exe1.setStyleSheet("color:white;")
        self.exe1.setObjectName("exe1")
        self.label_7 = QtWidgets.QLabel(self.ex1)
        self.label_7.setGeometry(QtCore.QRect(20, 90, 871, 561))
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.tabWidget.addTab(self.ex1, "")
        self.ex2 = QtWidgets.QWidget()
        self.ex2.setObjectName("ex2")
        self.tomain2 = QtWidgets.QPushButton(self.ex2)
        self.tomain2.setGeometry(QtCore.QRect(800, 670, 101, 41))
        self.tomain2.setStyleSheet("QPushButton {\n"
"  display: inline-block;\n"
"  color: white;\n"
"  text-decoration: none;\n"
"  user-select: none;\n"
"  outline: none;\n"
"  border: 2px solid white;\n"
"  border-radius: 1px;\n"
"  transition: 0.2s;\n"
"} \n"
"QPushButton:hover { background: rgba(255,255,255,.2); }\n"
"QPushButton:pressed { background: white; }")
        self.tomain2.setObjectName("tomain2")
        self.go2 = QtWidgets.QPushButton(self.ex2)
        self.go2.setGeometry(QtCore.QRect(680, 670, 101, 41))
        self.go2.setStyleSheet("QPushButton {\n"
"  display: inline-block;\n"
"  color: white;\n"
"  text-decoration: none;\n"
"  user-select: none;\n"
"  outline: none;\n"
"  border: 2px solid white;\n"
"  border-radius: 1px;\n"
"  transition: 0.2s;\n"
"} \n"
"QPushButton:hover { background: rgba(255,255,255,.2); }\n"
"QPushButton:pressed { background: white; }")
        self.go2.setObjectName("go2")
        self.exe2 = QtWidgets.QLabel(self.ex2)
        self.exe2.setGeometry(QtCore.QRect(10, 10, 901, 61))
        self.exe2.setStyleSheet("color:white;")
        self.exe2.setObjectName("exe2")
        self.pic2 = QtWidgets.QLabel(self.ex2)
        self.pic2.setGeometry(QtCore.QRect(20, 90, 871, 561))
        self.pic2.setText("")
        self.pic2.setObjectName("pic2")
        self.tabWidget.addTab(self.ex2, "")
        self.ex3 = QtWidgets.QWidget()
        self.ex3.setObjectName("ex3")
        self.tomain3 = QtWidgets.QPushButton(self.ex3)
        self.tomain3.setGeometry(QtCore.QRect(800, 670, 101, 41))
        self.tomain3.setStyleSheet("QPushButton {\n"
"  display: inline-block;\n"
"  color: white;\n"
"  text-decoration: none;\n"
"  user-select: none;\n"
"  outline: none;\n"
"  border: 2px solid white;\n"
"  border-radius: 1px;\n"
"  transition: 0.2s;\n"
"} \n"
"QPushButton:hover { background: rgba(255,255,255,.2); }\n"
"QPushButton:pressed { background: white; }")
        self.tomain3.setObjectName("tomain3")
        self.go3 = QtWidgets.QPushButton(self.ex3)
        self.go3.setGeometry(QtCore.QRect(680, 670, 101, 41))
        self.go3.setStyleSheet("QPushButton {\n"
"  display: inline-block;\n"
"  color: white;\n"
"  text-decoration: none;\n"
"  user-select: none;\n"
"  outline: none;\n"
"  border: 2px solid white;\n"
"  border-radius: 1px;\n"
"  transition: 0.2s;\n"
"} \n"
"QPushButton:hover { background: rgba(255,255,255,.2); }\n"
"QPushButton:pressed { background: white; }")
        self.go3.setObjectName("go3")
        self.pic3 = QtWidgets.QLabel(self.ex3)
        self.pic3.setGeometry(QtCore.QRect(20, 90, 871, 561))
        self.pic3.setText("")
        self.pic3.setObjectName("pic3")
        self.exe3 = QtWidgets.QLabel(self.ex3)
        self.exe3.setGeometry(QtCore.QRect(10, 10, 901, 61))
        self.exe3.setStyleSheet("color:white;")
        self.exe3.setObjectName("exe3")
        self.tabWidget.addTab(self.ex3, "")
        kontrless.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(kontrless)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 939, 21))
        self.menubar.setObjectName("menubar")
        kontrless.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(kontrless)
        self.statusbar.setObjectName("statusbar")
        kontrless.setStatusBar(self.statusbar)

        self.retranslateUi(kontrless)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(kontrless)

    def retranslateUi(self, kontrless):
        _translate = QtCore.QCoreApplication.translate
        kontrless.setWindowTitle(_translate("kontrless", "MainWindow"))
        self.label.setText(_translate("kontrless", "Контрольный урок."))
        self.textBrowser.setHtml(_translate("kontrless", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; font-weight:600; font-style:italic; color:#ffffff;\">Как играть?</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:22pt; color:#ffffff;\">В этом уроке можно использовать все возможные методы, изученные раньше, а именно:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:22pt; color:#ffffff;\">     1) Точка. Чтобы поставить точку необходимо нажать левой кнопкой мыши на выбранное место. Важно! Точки можно ставить только на ПЕРЕСЕЧЕНИИ прямых. (+ скрещивающиеся прямые также могут выглядеть пересекающимися на картинке)</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:22pt; color:#ffffff;\">     2) Отрезок.Чтобы построить отрезок, необходимо выбрать 2 точки левой кнопкой мыши и нажать &quot;Enter&quot;.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:22pt; color:#ffffff;\">     3) Прямая, параллельная данной. Чтобы построить прямую, параллельную данной, коснитесь левой кнопкой мыши прямой, затем какой-либо точки и нажмите &quot;Shift&quot;.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:22pt; color:#ffffff;\">     4) Прямая. Чтобы продлить отрезок до прямой необходимо выбрать прямую левой кнопкой мыши и нажать пробел.</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; color:#ffffff;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; color:#ffffff;\">Удачи!</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; color:#ffffff;\"><br /></p></body></html>"))
        self.tomain.setText(_translate("kontrless", "Главное меню"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.rules), _translate("kontrless", "Правила"))
        self.tomain1.setText(_translate("kontrless", "Главное меню"))
        self.go1.setText(_translate("kontrless", "Сдать"))
        self.exe1.setText(_translate("kontrless", "Задача:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ex1), _translate("kontrless", "Задача 1"))
        self.tomain2.setText(_translate("kontrless", "Главное меню"))
        self.go2.setText(_translate("kontrless", "Сдать"))
        self.exe2.setText(_translate("kontrless", "Задача:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ex2), _translate("kontrless", "Задача 2"))
        self.tomain3.setText(_translate("kontrless", "Главное меню"))
        self.go3.setText(_translate("kontrless", "Сдать"))
        self.exe3.setText(_translate("kontrless", "Задача:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ex3), _translate("kontrless", "Задача 3"))
